package:
  name: sanic
  version: "0.5.4"

source:
  fn: sanic-0.5.4.tar.gz
  url: https://pypi.python.org/packages/ad/7d/b5e4514a5742497c6847746619fad766ab71d954c2802c7e24695b193ba0/sanic-0.5.4.tar.gz
  md5: 2cddcbde4fd1ff4e53db1ee1e740c916
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch: python
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - sanic = sanic:main
    #
    # Would create an entry point called sanic that calls sanic.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - httptools >=0.0.9
    - ujson >=1.35
    - uvloop >=0.5.3

  run:
    - python
    - httptools >=0.0.9
    - uvloop >=0.5.3
    - ujson >=1.35
    - aiofiles >=0.3.0
    - websockets >=3.2

test:
  # Python imports
  imports:
    - sanic

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/channelcat/sanic/
  license: MIT License
  summary: 'A microframework based on uvloop, httptools, and learnings of flask'
  license_family: MIT

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
